version: "3.11"

services:
  db:
    container_name: gymlink-db
    image: postgres:alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - gymlink-data:/var/lib/postgresql/data
    networks:
      - gymlink-db
    restart: always

  backend:
    container_name: gymlink-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:1234
    networks:
      - gymlink-network 
      - gymlink-db
    depends_on:
      - db
    restart: always


networks:
  gymlink-network:
    external: true
  gymlink-db:
volumes:
  gymlink-data:
    driver: local
